INSERT INTO Tplant (TplantName, TplantDescription) VALUES
('Herb', 'Used for culinary or medicinal purposes'),
('Shrub', 'Small to medium-sized woody plant'),
('Tree', 'Large perennial plant with a trunk'),
('Succulent', 'Stores water in thick leaves'),
('Fern', 'Non-flowering plant with fronds'),
('Grass', 'Monocotyledonous green plant'),
('Vine', 'Climbing or trailing plant'),
('Bulb', 'Grows from underground storage organ'),
('Aquatic', 'Thrives in water environments'),
('Cactus', 'Spiny succulent adapted to arid climates'),
('Algae', 'Simple photosynthetic organism'),
('Moss', 'Small flowerless green plant'),
('Orchid', 'Exotic flowering plant'),
('Palm', 'Tropical tree with large leaves'),
('Bamboo', 'Fast-growing woody grass');

INSERT INTO Families (familyName, traits) VALUES
('Rosaceae', 'Flowering, often thorny, includes roses'),
('Fabaceae', 'Legumes, nitrogen-fixing roots'),
('Poaceae', 'Grasses, cereal crops'),
('Asteraceae', 'Daisy-like flowers, composite heads'),
('Cactaceae', 'Succulent, drought-resistant'),
('Orchidaceae', 'Complex flowers, epiphytic growth'),
('Lamiaceae', 'Aromatic herbs, square stems'),
('Fagaceae', 'Trees with nuts, like oaks'),
('Pinaceae', 'Conifers, needle-like leaves'),
('Brassicaceae', 'Edible leaves, cruciform flowers'),
('Solanaceae', 'Nightshades, includes tomatoes'),
('Apiaceae', 'Umbrella-shaped flowers, aromatic'),
('Cyperaceae', 'Sedges, grass-like wetland plants'),
('Araceae', 'Tropical, often with spathes'),
('Palmaceae', 'Tropical trees with fronds');

INSERT INTO Plants (plantName, plantType, plantFamily, plantCost, plantOrigin) VALUES
('Rose', 1, 1, 15, 'France'),
('Pea', 2, 2, 5, 'India'),
('Wheat', 6, 3, 3, 'Egypt'),
('Sunflower', 4, 4, 10, 'Ukraine'),
('Saguaro', 10, 5, 25, 'Arizona'),
('Orchid', 13, 6, 30, 'Thailand'),
('Mint', 1, 7, 8, 'Morocco'),
('Oak', 3, 8, 20, 'Germany'),
('Pine', 3, 9, 18, 'Canada'),
('Cabbage', 1, 10, 4, 'Russia'),
('Tomato', 1, 11, 6, 'Mexico'),
('Carrot', 1, 12, 5, 'Netherlands'),
('Papyrus', 9, 13, 12, 'Egypt'),
('Calla Lily', 4, 14, 22, 'South Africa'),
('Coconut Palm', 14, 15, 35, 'Sri Lanka');

INSERT INTO Stats (plantID, stat, statValue) VALUES
(1, 'Height', '1.2m'),
(2, 'Yield', '0.5kg'),
(3, 'GrowthRate', 'Fast'),
(4, 'Sunlight', 'Full'),
(5, 'WaterNeed', 'Low'),
(6, 'BloomTime', 'Spring'),
(7, 'Fragrance', 'Strong'),
(8, 'LeafType', 'Lobed'),
(9, 'Needles', 'Evergreen'),
(10, 'HarvestTime', 'Autumn'),
(11, 'FruitSize', 'Medium'),
(12, 'RootDepth', 'Deep'),
(13, 'Humidity', 'High'),
(14, 'Color', 'White'),
(15, 'FruitType', 'Drupe');

INSERT INTO CareTakes (plantID, careTakeDate, operation, commentary) VALUES
(1, '2025-09-01', 'Pruning', 'Removed dead branches'),
(2, '2025-09-02', 'Watering', 'Daily hydration'),
(3, '2025-09-03', 'Fertilizing', 'Added nitrogen-rich mix'),
(4, '2025-09-04', 'Weeding', 'Cleared surrounding area'),
(5, '2025-09-05', 'Repotting', 'Moved to larger container'),
(6, '2025-09-06', 'Spraying', 'Pest control applied'),
(7, '2025-09-07', 'Harvesting', 'Collected leaves'),
(8, '2025-09-08', 'Mulching', 'Added bark chips'),
(9, '2025-09-09', 'Trimming', 'Shaped canopy'),
(10, '2025-09-10', 'Watering', 'Twice a week'),
(11, '2025-09-11', 'Fertilizing', 'Organic compost'),
(12, '2025-09-12', 'Inspection', 'Checked for rot'),
(13, '2025-09-13', 'Cleaning', 'Removed algae'),
(14, '2025-09-14', 'Support', 'Staked upright'),
(15, '2025-09-15', 'Harvesting', 'Collected coconuts');